
import json, sys
from fpdf import FPDF
from datetime import datetime

data = json.load(open(r'C:\\Users\\leeak\\Alex\\Automation\\reports\\report-data-2026-03-08.json', 'r'))
news = data['news']
metrics = data['metrics']
date = data['date']

pdf = FPDF()
pdf.set_auto_page_break(auto=True, margin=20)
pdf.add_page()

# Header
pdf.set_fill_color(0, 0, 0)
pdf.rect(0, 0, 210, 35, 'F')
pdf.set_text_color(255, 255, 255)
pdf.set_font('Helvetica', 'B', 20)
pdf.set_y(8)
pdf.cell(0, 10, 'NAVADA', ln=True, align='L')
pdf.set_font('Helvetica', '', 9)
pdf.cell(0, 5, 'Weekly Intelligence Report  |  ' + date, ln=True, align='L')

# Reset colors
pdf.set_text_color(0, 0, 0)
pdf.ln(15)

# Job Pipeline
pdf.set_font('Helvetica', 'B', 14)
pdf.cell(0, 8, 'JOB PIPELINE', ln=True)
pdf.set_draw_color(0, 0, 0)
pdf.line(10, pdf.get_y(), 200, pdf.get_y())
pdf.ln(4)
pdf.set_font('Helvetica', '', 11)
pdf.cell(95, 7, f"Total jobs tracked: {metrics.get('total', 0)}", ln=False)
pdf.cell(95, 7, f"New this week: {metrics.get('thisWeek', 0)}", ln=True)
pdf.cell(95, 7, f"Applied: {metrics.get('Applied', 0)}", ln=False)
pdf.cell(95, 7, f"Interviews: {metrics.get('Interview', 0)}", ln=True)
pdf.cell(95, 7, f"Shortlisted: {metrics.get('Shortlisted', 0)}", ln=False)
pdf.cell(95, 7, f"Offers: {metrics.get('Offer', 0)}", ln=True)
pdf.ln(8)

# Top Companies
if metrics.get('topCompanies'):
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 7, 'Top Companies This Week:', ln=True)
    pdf.set_font('Helvetica', '', 10)
    for c in metrics['topCompanies']:
        pdf.cell(0, 6, f"  - {c}", ln=True)
    pdf.ln(6)

# AI News
pdf.set_font('Helvetica', 'B', 14)
pdf.cell(0, 8, 'AI INDUSTRY NEWS', ln=True)
pdf.line(10, pdf.get_y(), 200, pdf.get_y())
pdf.ln(4)
pdf.set_font('Helvetica', '', 10)
for i, article in enumerate(news[:10]):
    pdf.set_font('Helvetica', 'B', 10)
    title = article['title'][:80] + ('...' if len(article['title']) > 80 else '')
    pdf.cell(0, 6, f"{i+1}. {title}", ln=True)
    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, f"   {article.get('source', '')}", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

# Footer
pdf.ln(10)
pdf.set_font('Helvetica', 'I', 8)
pdf.set_text_color(150, 150, 150)
pdf.cell(0, 5, 'Generated by Claude | AI Chief of Staff | NAVADA', ln=True, align='C')
pdf.cell(0, 5, f"Report date: {datetime.now().strftime('%d %B %Y %H:%M')}", ln=True, align='C')

pdf.output(r'C:\\Users\\leeak\\Alex\\Automation\\reports\\weekly-report-2026-03-08.pdf')
print('PDF generated')
