#!/usr/bin/env node
/**
 * ccusage Session Report — Run at start/end of Claude Code sessions
 * Tracks Claude token usage and costs across all users and interactions.
 *
 * Usage:
 *   node ccusage-report.js              # Daily report (default)
 *   node ccusage-report.js weekly       # Weekly report
 *   node ccusage-report.js monthly      # Monthly report
 *   node ccusage-report.js --email      # Daily report + email to Lee
 *   node ccusage-report.js --json       # Output as JSON
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const LOG_DIR = path.join(__dirname, 'logs');
const LOG_FILE = path.join(LOG_DIR, 'ccusage-reports.jsonl');

const args = process.argv.slice(2);
const period = ['weekly', 'monthly', 'session'].find(a => args.includes(a)) || 'daily';
const asJson = args.includes('--json');
const sendEmail = args.includes('--email');

async function run() {
  try {
    // Run ccusage
    const cmd = asJson
      ? `ccusage ${period} --json --no-color`
      : `ccusage ${period} --no-color`;

    console.log(`[ccusage] Running ${period} report...`);
    const output = execSync(cmd, {
      encoding: 'utf-8',
      timeout: 30000,
      env: { ...process.env, NO_COLOR: '1' },
    });

    // Log to JSONL
    if (!fs.existsSync(LOG_DIR)) fs.mkdirSync(LOG_DIR, { recursive: true });
    const entry = {
      timestamp: new Date().toISOString(),
      period,
      report: output.slice(0, 5000),
    };
    fs.appendFileSync(LOG_FILE, JSON.stringify(entry) + '\n');

    console.log(output);

    // Email report if requested
    if (sendEmail) {
      try {
        const emailService = require('./email-service');
        const cleanOutput = output.replace(/\x1b\[[0-9;]*m/g, ''); // strip ANSI
        const htmlBody = `
          <div style="font-family: monospace; background: #0a0a0a; color: #e0e0e0; padding: 24px; border-radius: 8px;">
            <h2 style="color: #00d4ff; margin-top: 0;">Claude Code Token Usage | ${period.charAt(0).toUpperCase() + period.slice(1)} Report</h2>
            <pre style="white-space: pre-wrap; font-size: 13px; line-height: 1.5;">${cleanOutput}</pre>
            <hr style="border-color: #333;">
            <p style="color: #888; font-size: 11px;">Generated by ccusage on ${new Date().toLocaleString('en-GB', { timeZone: 'Europe/London' })}</p>
          </div>`;
        await emailService.sendEmail({
          to: 'leeakpareva@gmail.com',
          subject: `Claude Token Usage | ${period.charAt(0).toUpperCase() + period.slice(1)} Report | ${new Date().toLocaleDateString('en-GB')}`,
          html: htmlBody,
        });
        console.log('[ccusage] Report emailed to Lee.');
      } catch (emailErr) {
        console.error('[ccusage] Email failed:', emailErr.message);
      }
    }

    return output;
  } catch (err) {
    console.error('[ccusage] Error:', err.message);
    process.exit(1);
  }
}

run();
