/**
 * NAVADA Voice Service
 * Generate voice notes via OpenAI TTS and send as email attachments
 * Voice: Claude, AI Chief of Staff
 */

require('dotenv').config({ path: __dirname + '/.env' });
const fs = require('fs');
const path = require('path');
const axios = require('axios');
const { sendEmail, p } = require('./email-service');

const VOICE_DIR = path.join(__dirname, 'voice-notes');
if (!fs.existsSync(VOICE_DIR)) fs.mkdirSync(VOICE_DIR, { recursive: true });

const API_KEY = process.env.OPENAI_API_KEY_VOICE;

/**
 * Generate a voice note MP3 using OpenAI TTS
 * @param {string} text - Text to speak
 * @param {string} voice - Voice: alloy, echo, fable, onyx, nova, shimmer (default: onyx)
 * @param {string} model - tts-1 or tts-1-hd (default: tts-1-hd)
 * @returns {string} Path to saved MP3
 */
async function generateVoice(text, voice = 'onyx', model = 'tts-1-hd') {
  const response = await axios.post(
    'https://api.openai.com/v1/audio/speech',
    { model, voice, input: text },
    {
      headers: {
        'Authorization': `Bearer ${API_KEY}`,
        'Content-Type': 'application/json',
      },
      responseType: 'arraybuffer',
    }
  );

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const filename = `voice-note-${timestamp}.mp3`;
  const filepath = path.join(VOICE_DIR, filename);
  fs.writeFileSync(filepath, Buffer.from(response.data));
  console.log(`Voice note saved: ${filepath} (${(response.data.byteLength / 1024).toFixed(1)}KB)`);
  return filepath;
}

/**
 * Send a voice note email
 * @param {Object} opts
 * @param {string} opts.to - Recipient email
 * @param {string} opts.subject - Email subject
 * @param {string} opts.message - Text message (also converted to speech)
 * @param {string} opts.voice - TTS voice (default: onyx)
 */
async function sendVoiceEmail({ to, subject, message, voice = 'onyx' }) {
  console.log('Generating voice note...');
  const audioPath = await generateVoice(message, voice);

  console.log('Sending email with voice attachment...');
  await sendEmail({
    to,
    subject,
    heading: subject,
    type: 'general',
    body: [
      p('Lee,'),
      p('Voice note attached. Play the MP3 to hear the message.'),
      p(`<em style="color:#888; font-size:13px;">"${message}"</em>`),
    ].join(''),
    attachments: [
      {
        filename: 'claude-voice-note.mp3',
        path: audioPath,
        contentType: 'audio/mpeg',
      },
    ],
    footerNote: 'Voice generated by OpenAI TTS (HD) &middot; Voice: ' + voice,
  });

  return audioPath;
}

module.exports = { generateVoice, sendVoiceEmail };

// --- CLI ---
if (require.main === module) {
  const args = process.argv.slice(2);
  if (args.length < 2) {
    console.log('Usage: node voice-service.js <to> <message> [voice]');
    console.log('Voices: alloy, echo, fable, onyx, nova, shimmer');
    process.exit(0);
  }
  const [to, message, voice] = args;
  sendVoiceEmail({ to, subject: 'Voice Note from Claude', message, voice })
    .then(() => { console.log('Done.'); process.exit(0); })
    .catch(e => { console.error('Failed:', e.message); process.exit(1); });
}
